Added a solution for task 08-authentication/01-local
js-tasks-ru/nodejs-20201020_n-belozyorova pull request #8
Opened 2020-11-13 13:59 UTC by belozyorovany

2020-11-13 14:28 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
+ стратегия должна возвращать ошибку если указан несуществующий email
+ стратегия должна возвращать ошибку если указан неверный пароль
+ стратегия должна возвращать объект пользователя если email и пароль верные
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-14 17:17 UTC, tadjik1 commented on 08-authentication/01-local/libs/strategies/local.js
> +      User.findOne({email: email }, async function (err, user) {
в вашем коде есть обработка потенциальных ошибок при выполнении запроса к базе данных, но нет обработки возможных ошибок при проверке пароля (`await user.checkPassword(password);`). в реальной жизни такая ошибка может привести к падению всего процесса nodejs.

в целом я обычно рекомендую не смешивать async/await и коллбеки. так уж вышло, что здесь без коллбека не обойтись (так passport работает), но по крайней мере свою логику можно всю завернуть в async/await и использовать единый стиль для обработки ошибок.

2020-11-14 17:17 UTC, tadjik1 requested changes
@belozyorovany отличное решение, в целом верное 👍 
осталось исправить лишь небольшой момент, связанный с обработкой ошибок.

2020-11-14 20:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Настройка локальной стратегии
+ поле usernameField должно должно содержать email
+ стратегия должна возвращать ошибку если указан несуществующий email
+ стратегия должна возвращать ошибку если указан неверный пароль
+ стратегия должна возвращать объект пользователя если email и пароль верные
```
```diff
Использование социальных сетей для аутентификации пользователей
- функция authenticate должна возвращать ошибку, если email не передаётся
- функция authenticate должна создавать пользователя если его еще нет
- функция authenticate выбрасывает ошибку если email невалидный
- функция authenticate возвращает пользователя, который уже есть в базе
```

2020-11-15 10:11 UTC, tadjik1 commented
@belozyorovany всё отлично, решение первой задачи выполнено на 100% верно. так как вы добавили еще одну задачу, то её тоже надо решить, чтобы оба решения могли быть засчитаны.

2020-11-15 21:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-16 11:28 UTC, tadjik1 approved these changes
@belozyorovany  👍

2020-11-16 11:29 UTC, merged